### ISSUE TITLE
Can't run mltrain script locally due to <3 arguments

### ISSUE THREAD

**Issue by ghost** [GoogleCloudPlatform/tensorflow-recommendation-wals#8]
There are only two parameteres for the mltrain script if you want to run it locally: 'local' and the path to the data. However, in your mltrain script you don't allow for less than three arguments passed:
`
if [[ $# < 3 ]]; then
  usage
  exit 1
fi
`
I have to add a bogus argument to get this to work.
Ex: `mltrain.sh local data.csv` does not work
Ex: `mltrain.sh local garbage data.csv` does work

**Comment by AsiehH** [comment]
I had the same problem. 
Unfortunately there is a typo in the following command :

`./mltrain.sh local ../data/recommendation_events.csv --data-type web_views --use-optimized
`

The fix is to change `data/` to `data ` as follows:

`./mltrain.sh local ../data recommendation_events.csv --data-type web_views --use-optimized`

If you are also running the [4-part solution tutorial](https://cloud.google.com/solutions/machine-learning/recommendation-system-tensorflow-overview), I have also found a typo in part 3. You can look at this issue: 
https://github.com/GoogleCloudPlatform/tensorflow-recommendation-wals/issues/9

If this answers your question, you can close the issue. 
Thanks
